package utils.enums

enum class ModulePath(val path: String) {
    COMPOSE_APP(":composeApp"),
    SERVER(":server"),
    SHARED(":shared"),
    STORES_ATHLETICA_PLUS(":stores:athletica-plus"),
    STORES_NUTRI_SPORT(":stores:nutri-sport"),
    DI(":di"),
    CORE_PRESENTATION(":core:presentation"),
    CORE_UTILS(":core:utils"),
    CORE_RESOURCES(":core:resources"),
    CORE_NAVIGATION(":core:navigation"),
    CORE_DATA(":core:data"),
    CORE_DOMAIN(":core:domain"),
    CORE_SECURITY(":core:security"),
    CORE_NETWORK(":core:network"),
    FEATURE_AUTHENTICATION_DATA(":feature:authentication:data"),
    FEATURE_AUTHENTICATION_DOMAIN(":feature:authentication:domain"),
    FEATURE_AUTHENTICATION_PRESENTATION(":feature:authentication:presentation"),
    FEATURE_HOME_DATA(":feature:home:data"),
    FEATURE_HOME_DOMAIN(":feature:home:domain"),
    FEATURE_HOME_PRESENTATION(":feature:home:presentation"),
    TEST(":test"),
}