ktor {
    deployment {
        port = 8080
        host = "0.0.0.0"
        behindProxy = false
        behindProxy = ${?BEHIND_PROXY}
    }
    application {
            modules = [ org.cmp.store.ApplicationKt.main ]
    }
}

db {
    url = "jdbc:sqlite:./store.db"
    driver = "org.sqlite.JDBC"
    recreateSchema = false
    recreateSchema = ${?RECREATE_SCHEMA}
}

jwt {
    realm = "CMP Store"
}
